name: Semantic-release update changelog
on:
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  release:
    name: Release
    if: ${{ ! contains(github.event.pull_request.labels.*.name, 'skip-release') }} 
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install @semantic-release/changelog -D  
          npm install @semantic-release/git -D
          npm i conventional-changelog-conventionalcommits
          npx semantic-release@17
          
          
